version: 2
jobs:
  build:
    working_directory: ~/docker-antivirus
    docker:
      - image: centos:latest
    steps:
      - checkout
      - run:
          name: Install EPEL
          command: 'yum install -y epel-release'
      - run:
          name: Install dependancies
          command: 'yum install -y gcc-c++ make ruby ruby-devel coreutils clamav atomic docker'
      - type: setup_remote_docker
      - run:
          name: Install Bundler
          command: 'gem install bundler'
      - run:
          name: Bundle install
          command: 'bundle install'
      - run:
          name: Integration tests
          command: 'bundle exec rspec'
